# Configuration file to run NHL as a standalone module, outside of FETCH3

model_options:
  #INPUT DATA FILE PARAMETERS
  ###########################

  # File for input met data
  input_fname: "UMBS_flux_2011.csv"  #TODO

  # Start and end in the fetch2 example
  # start_time: "2011-06-09 00:00:00" #begining of simulation #DOY 160
  # end_time: "2011-07-10 00:00:00" #end #DOY190 - 7/10 is doy 191
  start_time: "2011-01-01 00:00:00" #begining of simulation #DOY 160
  end_time: "2012-01-01 00:00:00" #end #DOY190 - 7/10 is doy 191

  dt:  1800  #seconds - input data resolution


  #SITE INFORMATION
  #################
  latitude:  45.5598  # From AmeriFlux UMBS page
  longitude:  -84.7138
  time_offset:  -5 #Offset from UTC time, e.g EST = UTC -5 hrs

  # Method to use for zenith angle calculation (if using NHL)
  zenith_method: "fetch2"

  #NUMERICAL SOLUTION TIME AND SPACE CONSTANTS (dz and dt0)
  #########################################################
  #The finite difference discretization constants
  dt0:  20  #model temporal resolution [s] #TODO check matlab code
  dz:  0.2  #model spatial resolution [m] #from fetch2 example

  # TREE INFO
  species:  "Oak"
  LAD_norm:  'LAD_data.csv' #LAD data


parameters:

  #TREE PARAMETERS
  Hspec: 22                      #Height average of trees [m]
  #From NHL code
  LAI: 37.8507360000000                      #[-] Leaf area index

  #########################################################################3
  #NHL PARAMETERS
  ###########################################################################
  scale_nhl:  1

  sapwood_area: 0.0177
  theta_sat_x: 573 # Pa
  taper_top: 0.2

  mean_crown_area_sp:  26.8600000000000 #from NHL
  total_crown_area_sp:  2171.75744784689 #from NHL code
  plot_area:  75649.5511
  sum_LAI_plot:  3.7850736000000005

  Cd:  0.2 # Drag coefficient Note: NHL forcing says 0.1, but i think it uses 0.2
  alpha_ml:  0.1  # Mixing length constant
  Cf:  0.85  #Clumping fraction [unitless], assumed to be 0.85 (Forseth & Norman 1993) unless otherwise specified
  x:  6.67330000000000 #Ratio of horizontal to vertical projections of leaves (leaf angle distribution), assumed spherical (x=1)

  Vcmax25:  59.9300000000000
  alpha_gs:  6.67330000000000
  alpha_p:  1